title : Aaron Maturen
tagline: Blog Tagline
author : Aaron Maturen
  name : Aaron Maturen
  email : aaron.maturen@gmail.com
  github : aaronmaturen
  twitter : atmaturen
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
