title : Aaron Maturen
tagline: Blog Tagline
author :
  name : Aaron Maturen
  email : aaron.maturen@gmail.com
  github : aaronmaturen
  twitter : atmaturen
  feedburner : feedname

navigation :
	- presentations.md
	- projects.md
#  - archive.html
#  - tags.html
#  - categories.html
#  - pages.html
  - about.md
  
